version: '3'
services:
  db:
    container_name: postgres
    image: postgres:11
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
      - ${HOME}/.postgresql/server.crt:/var/lib/postgresql/server.crt
      - ${HOME}/.postgresql/server.key:/var/lib/postgresql/server.key
    environment:
      # - POSTGRES_HOST_AUTH_METHOD=trust # Development
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256 # Production
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    # For the authentication method
    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key -c password_encryption=scram-sha-256

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    # command: uvicorn app.main:app --host '0.0.0.0' --port 8000 # Production
    command: uvicorn app.main:app --host '0.0.0.0' --port 8000 --reload # Development
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      HOST: ${HOST}
      PORT: 8000

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    user: "node"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    command: "yarn start"
    ports:
      - "9999:9999"
    depends_on:
      - backend

# Declaration of the named volume
volumes:
  db_data:
