version: '3'
services:
  db:
    container_name: postgres
    image: postgres:11
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: uvicorn app.main:app --host '0.0.0.0' --port 8000
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    user: "node"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    command: "yarn start"
    ports:
      - "9999:9999"
    depends_on:
      - backend
