"""fix relations 3

Revision ID: 0afa2b5597f0
Revises: 23ea5a5f0939
Create Date: 2024-05-05 17:24:55.904780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0afa2b5597f0'
down_revision: Union[str, None] = '23ea5a5f0939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
