"""fix a column in confidence_levels

Revision ID: 2982f9eb827d
Revises: 223b2642a6fb
Create Date: 2024-05-04 16:49:38.940087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2982f9eb827d'
down_revision: Union[str, None] = '223b2642a6fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('confidence_level_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'cards', 'confidence_levels', ['confidence_level_id'], ['id'])
    op.add_column('confidence_levels', sa.Column('is_default', sa.Boolean(), nullable=False))
    op.add_column('confidence_levels', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'confidence_levels', 'users', ['user_id'], ['id'])
    op.drop_constraint('review_schedules_confidence_level_id_fkey', 'review_schedules', type_='foreignkey')
    op.drop_column('review_schedules', 'confidence_level_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_schedules', sa.Column('confidence_level_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('review_schedules_confidence_level_id_fkey', 'review_schedules', 'confidence_levels', ['confidence_level_id'], ['id'])
    op.drop_constraint(None, 'confidence_levels', type_='foreignkey')
    op.drop_column('confidence_levels', 'user_id')
    op.drop_column('confidence_levels', 'is_default')
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_column('cards', 'confidence_level_id')
    # ### end Alembic commands ###
