"""fix user in in review schedule

Revision ID: 77049327f5d1
Revises: 6082b098113e
Create Date: 2024-05-05 17:12:09.549457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77049327f5d1'
down_revision: Union[str, None] = '6082b098113e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('review_schedules_user_id_fkey', 'review_schedules', type_='foreignkey')
    op.create_foreign_key(None, 'review_schedules', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review_schedules', type_='foreignkey')
    op.create_foreign_key('review_schedules_user_id_fkey', 'review_schedules', 'cards', ['user_id'], ['id'])
    # ### end Alembic commands ###
